# Generated by Django 2.0.2 on 2018-02-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_base_classes', '0003_auto_20180208_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childa',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_base_classes_childa_set', related_query_name='abstract_base_classes_childa', to='abstract_base_classes.Other'),
        ),
        migrations.AlterField(
            model_name='childb',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_base_classes_childb_set', related_query_name='abstract_base_classes_childb', to='abstract_base_classes.Other'),
        ),
    ]
