# Generated by Django 2.0.2 on 2018-02-06 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0007_auto_20180206_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_from_user', to='many_to_many.TwitterUser'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_to_user', to='many_to_many.TwitterUser'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='relations',
            field=models.ManyToManyField(related_name='_twitteruser_relations_+', through='many_to_many.Relation', to='many_to_many.TwitterUser'),
        ),
    ]
