# Generated by Django 2.0.2 on 2018-02-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_table', '0002_auto_20180209_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', related_query_name='place', to='multi_table.Other'),
        ),
    ]
